//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonSistemi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneOtomasyonSistemiEntities1 : DbContext
    {
        public HastaneOtomasyonSistemiEntities1()
            : base("name=HastaneOtomasyonSistemiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_DOKTOR> TBL_DOKTOR { get; set; }
        public virtual DbSet<TBL_DOKTOR_UNVAN> TBL_DOKTOR_UNVAN { get; set; }
        public virtual DbSet<TBL_HASTA> TBL_HASTA { get; set; }
        public virtual DbSet<TBL_HASTA_HESAP> TBL_HASTA_HESAP { get; set; }
        public virtual DbSet<TBL_ISLEM> TBL_ISLEM { get; set; }
        public virtual DbSet<TBL_KONTROL> TBL_KONTROL { get; set; }
        public virtual DbSet<TBL_POLİKİNLİK> TBL_POLİKİNLİK { get; set; }
        public virtual DbSet<TBL_RANDEVU> TBL_RANDEVU { get; set; }
        public virtual DbSet<TBL_SEHIR> TBL_SEHIR { get; set; }
        public virtual DbSet<TBL_SEKRETER> TBL_SEKRETER { get; set; }
    }
}
