//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HASTA_HESAP
    {
        public int HASTA_HESAP_ID { get; set; }
        public string KULLANICI_AD { get; set; }
        public string SİFRE { get; set; }
    }
}
