//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HASTA
    {
        public string TC { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public string TELNO { get; set; }
        public Nullable<int> SEHIR_ID { get; set; }
        public Nullable<int> HASTA_HESAP_ID { get; set; }
    
        public virtual TBL_SEHIR TBL_SEHIR { get; set; }
    }
}
