//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RANDEVU
    {
        public byte RANDEVU_ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.TimeSpan> SAAT { get; set; }
        public Nullable<int> POLIKINLIK_ID { get; set; }
        public Nullable<int> HASTAHESAP_ID { get; set; }
        public Nullable<int> DOKTORHESAP_ID { get; set; }
    }
}
